// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StapleIT.DAL;

#nullable disable

namespace StapleIT.Migrations
{
    [DbContext(typeof(StapleITContext))]
    [Migration("20230312194136_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StapleIT.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("StapleIT.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("StapleIT.Models.List", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListId"));

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserGroupId")
                        .HasColumnType("int");

                    b.HasKey("ListId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("List");
                });

            modelBuilder.Entity("StapleIT.Models.ListDetail", b =>
                {
                    b.Property<int>("ListDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListDetailId"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ListId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ListDetailId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ListId");

                    b.ToTable("ListDetail");
                });

            modelBuilder.Entity("StapleIT.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailAdd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("StapleIT.Models.UserGroup", b =>
                {
                    b.Property<int>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGroupId"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserGroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("StapleIT.Models.List", b =>
                {
                    b.HasOne("StapleIT.Models.UserGroup", null)
                        .WithMany("List")
                        .HasForeignKey("UserGroupId");
                });

            modelBuilder.Entity("StapleIT.Models.ListDetail", b =>
                {
                    b.HasOne("StapleIT.Models.Item", null)
                        .WithMany("ListDetail")
                        .HasForeignKey("ItemId");

                    b.HasOne("StapleIT.Models.List", null)
                        .WithMany("ListDetail")
                        .HasForeignKey("ListId");
                });

            modelBuilder.Entity("StapleIT.Models.UserGroup", b =>
                {
                    b.HasOne("StapleIT.Models.Group", null)
                        .WithMany("UserGroup")
                        .HasForeignKey("GroupId");

                    b.HasOne("StapleIT.Models.User", null)
                        .WithMany("UserGroup")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StapleIT.Models.Group", b =>
                {
                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("StapleIT.Models.Item", b =>
                {
                    b.Navigation("ListDetail");
                });

            modelBuilder.Entity("StapleIT.Models.List", b =>
                {
                    b.Navigation("ListDetail");
                });

            modelBuilder.Entity("StapleIT.Models.User", b =>
                {
                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("StapleIT.Models.UserGroup", b =>
                {
                    b.Navigation("List");
                });
#pragma warning restore 612, 618
        }
    }
}
